services:
  sanitizelinkbot:
    build: .
    container_name: sanitizelinkbot
    env_file:
      - .env
    volumes:
      - bot-data:/app/data
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  bot-data:
